stages:
  - build 
  - test

# 1. Build & Push to Docker Hub
build_images:
  stage: build
  tags:
    - dev-laptop
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      command: ["--tls=false"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    #Docker hub login
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

    # Backend Docker Image build and push
    - docker build -t "$DOCKER_USER/feedback-backend:latest" ./gitops/apps/feedback-dev/backend
    - docker push "$DOCKER_USER/feedback-backend:latest"

    # Worker Docker Image build and push
    - docker build -t "$DOCKER_USER/feedback-worker:latest" ./gitops/apps/feedback-dev/worker
    - docker push "$DOCKER_USER/feedback-worker:latest"

    #Frontend Docker Image build and push
    - docker build -t "$DOCKER_USER/feedback-frontend:v1" ./gitops/apps/feedback-dev/frontend
    - docker push "$DOCKER_USER/feedback-frontend:v1"


# 2. Security & Quality Scan
sonarqube_scan:
  stage: test
  tags:
    - dev-laptop
  image: 
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"  # This pulls all history so SonarQube is happy
  script:
    - sonar-scanner 
      -Dsonar.projectKey=Feedback-Application
      -Dsonar.sources=./gitops/
      -Dsonar.host.url=$SONAR_HOST_URL 
      -Dsonar.login=$SONAR_TOKEN 
      -Dsonar.qualitygate.wait=true  
