apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: feedback-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: faizalaccount/feedback-worker:v2
        env:
          - name: DB_HOST
            value: "postgres"
          - name: DB_USER
            value: "admin"
          - name: DB_PASSWORD
            value: "admin123"
          - name: DB_NAME
            value: "feedback_db"