---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-pass
  namespace: default
spec:
  encryptedData:
    password: AgCPaOR+RXFsCrpwAHJVfABhkIZ0C39nLYsQ6P7LYGpJXK5K7ujGN4cWDLi591DdY6RhwJjieDk9TcsVwgLvgDZd0o6DFNrN04i/rbcFkcncmf7i2522mGwWKr7g5hAuTLhQNxHiocXdZfRtvQJZQG2HSZGpGZwFF2J+dSsghhFOdOyV74EwmD1v+j80UYX62CvsT8lOIHV8j/7Y2Q8E5nAXMtpTX6J6AplWRFwa3b6DhNyJ8hWW47YJOY5tsgH8nHgLhycPiWqQDW84PaKb9Hfobzmm7DOQsqsS3IRTbJfaAV0KXPtOlnlPgQrdOJyZjln4m69cOBtoS7namvI7KZBjViwOOa/cAN9FSiMbP9xOog/zq8Jv42JRmdGr8kZeKT1Gen33dbt6HQZZHYhu2yRhthDgoHKe2aP3xrVNo3dxuwQbW/8925vvj9JEQV2xQgzQgmFUKCdrWMv5C7TvpJ6O4H62X5l7H/5yyZjv8NkYy1w54Ru9D7mKRRCb8AkmN3IqXjXJvVZxs6AfrRgVRyCvGUWmt4ZSSsU+fSZFwtigmbi/nhW4tYllS99wP2JcN5snaBaZSDpqbCZMkK4iMHCFDIyocxAboeRNoAG+T5zhnEbD0A9Fw622A2zAId1CyQYgrBl0ze/8v4c7xKaQ0IdENLRIPl6ZVN7r+BoIS5vPyjjIBs9gOz7/IUviasvH90ZUoFeBH+A89haS08+vTA8Kpi9eNFUD/YQ=
  template:
    metadata:
      name: mongodb-pass
      namespace: default
    type: Opaque
