---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-pass
  namespace: feedback-dev
spec:
  encryptedData:
    password: AgAvSB65HfB0SqczJOVXvL/kNK+As0fS+PddnrBjVXGBCVREbwayarMmxZjyJfogT7jJ1RasJ8ZT9LaFr5G35OqSDWMcy7GkKN6/fCDxOyKMwS3Z2iEJtHvxokcycmLpDQnLBqcXln02DV6siBibfWfruarFAG/BGeX1a1yw9lD4Pt6+d6RYKYYrCsLtQsc0WPQhYnDmuzydxbP/l+b+oOzuaaLA+l0xpag207ygNHVlqKue7+p9/GroCk7i7F5YklRE6rf+XtGJRUlU5BdJSkPL78yuap+AzoVXd2FaMyl3ZEWKYdn1T8JPAga0LardHYIVusiFy3FvX2fe80bC6uJrHcov0fBjkgFyWyJ9AMVrqhCGds3mvwyoCcOjlbmnmRDl+ib78xKptCMppZTnU6bJWQ2i+3TWODh5pJ2UK01l2QIV/0SVpxwFPykH8EEm70i/xrOL/ahbuforS8j2nRlABF2pUQddR5+ZKuuld+bHeZm6xkTsBtupl5bj0e8xwrZanBKpyxNpHawlmu3LRX/rOBQO97CVgx+46BkdTtyEy72OmzdOeXZMidkuYk6/AS97qLa9+272+bsvJrNUrbPo0bO3wD4Axtf2EgtGGMkz2luVQpFkCb9D5VkrRKfq7nrpTy5dS2sjCo90I7/SbJZIOao9Kkel1c21tdUhJe88xskNzaXFMbwQojpStzCgvfsMAWpL2E1k72inUeUnhrNBwDIr0TQ4rPo=
  template:
    metadata:
      name: mongodb-pass
      namespace: feedback-dev
    type: Opaque
