apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: feedback-dev
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/imranafset/Feedback-Application.git
    targetRevision: main
    path: gitops/apps/feedback-dev

  destination:
    server: https://kubernetes.default.svc
    namespace: feedback-dev

  # Add this section to fix form submit
  ignoreDifferences:
    - group: cert-manager.io
      kind: Certificate
      jsonPointers:
        - /status

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # Add this sync option 
      - RespectIgnoreDifferences=true