---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-secret
  namespace: feedback-dev
spec:
  encryptedData:
    url: AgCpPiQCGhOwev+eMkZI+9QQ708y7dzoQOKYCDjP34w7wYSJngOFdxE6+AH+zkjnv39TmQDCtWMrjDGUUmlwh24KbZa0Y/c0R8b6siInS7vZj0fvUNX0JuM8787zSdpw2VUjf/GLuPtj9B4Gt2d22ahHmIH17bl8FQIb4rP6Soi/ScZx7X9tGsRe4wOSHBDwFo+XwSTvDOTMfqSEA6jRCJ/Z2HCyscJgvwgVlRnEiohrYlm4SXFaS/IBPpWAQTwtUyiR0kxUqoih2YEvUCLS8t7LxfccRerOccB3zGpi7lathP/cdryPQ7DDoAuBaNJghudNlvWbLOYOIqk1iarV8YmNb9Q8FNT+srxVkeZtgO5s5joCOHdv2KucpbPpm8Dyu7LbWI47v5VGHnJTS/hZfYb+MdLA3qET5aN8x/zFJvz5obYUxZVo10KF/EdPEbq3xj0Vw6zTiCowPqQE4x3t6x+F1ZefJQsBHM88DA/+brx+Aq5K/9JtRjYQ1W04K7VR7TicYzVPDv1bSanAv3nNBIBLUeB7DENgsAIpidHk7FPByb+ELTM3L4zo7jmL9uq1j0hF9Z7Y6A7ri4/0EO7JiV2pjKMZZienl53EmMcdBxu9atobMKr0BOllDH3ROjHgO71+3hn6BKSEk9puarC4daPCn2iF0/00x00UO8JgUbRcdwr62yMcV4OXcl0QCK6uHyPKklVYVZWI1Ew9PS6GzAUDSeCBE3hvql8yZEucrBXLnrM=
  template:
    metadata:
      name: rabbitmq-secret
      namespace: feedback-dev
    type: Opaque
