---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-secret
  namespace: feedback-dev
spec:
  encryptedData:
    url: AgAzQxjV8d5D4BCjY626GYKUdLxVeonB+aLNwtwO8gteBicJqIpntKlTK4156kSus/cfJy6/I36Br4ZRtGHCRY/Ot/KuEYZWB69v+cw3E1A+M2ITM1CfwxwKX6tjyCD0azCvM0FPzDlKQIItRqFghcNbjRCHPBPU3dmrmZYIkwIMsb4n85tmP5CfUFzsuupDHX07qg2LkqdcwBR3f2dAADKg10H0YYZNVd9ck/LGzRaMqPDpbucX9HuRiWQRxPlRuPUxsIGKmeqZkbs2ssAZk87SFTRfZPSG8Y2d5imnjekrMaJcsQwuiNogZ4eI0EU+1/hSHxLATdeRIXInjKUFtJ/2Mx8aD1YhbYvwzAZPMXcTvREX1ivDmtzYZOTPycO0/4ZCX8e7cR5B8UHM+s5ZXMHs8XJRCokPibLerRXoQBzsam+0Z1YA+/b+iMGdPU67/Hd8ibLLiBTRESQRGy/vU2kdF6JtxXTL1ItdOC9x9HcU24a25AgNpCMm3yiq9iWE+O1YNEhEMEf9QRZzz/CqMuqRhgZzPp5dFAle8IpGb4Wqpxf1qdkxlcDsV5TOd9NK8AQZHbHd5odHSAI1ztLsUR4+vn8if7SFujyo1un7vLnGLegBMNuCsXRmbaH0vCXIbHpQteBpv8zCUKqqCeSsQfVohYVGeoIR5099y/qS34L5IeSg1h7owNqhvnKMgjVBU5NCAqYcm6CisvnqIw/HRmxIy0I2cIZfLRYzCI12Qto2BEg=
  template:
    metadata:
      name: rabbitmq-secret
      namespace: feedback-dev
    type: Opaque
