---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-secret
  namespace: feedback-dev
spec:
  encryptedData:
    url: AgAagZGlM0jQM9fpCuZopBCntw/T2AsZrWeu1r4aQE7SI1sPDafkp1XSoU8t39Yt4O6QdgYlLshnX7pGSIilMzZfkKcy4jCaoqV8k3MLNDFt+QEtTQrRnMuFbCRDQXnMQkpMr4c8Mgr1KbSNpyfoHDJG2dLoK97aoUNZ5BMSdibVvOgNJ4NJcOontK4FZH26gRr+67PABz7aztL72hJaZLVOatBe76jWnqtjSiNFui4SbWjKFj7Sx77HoQ6pcVEyOifAefraLfYRlR62e2PMnqLChskyDWragZov4GppaLKza97Pz2ZLAXCTnyhkNxbm1REXJ1eWK+2CCuJ/8/1Bbaw5ezOR9IwrK87ZfuyaGG9L++DeAe4lxk7xmW9adTnMjaxpL60zR0q10MHErV4P7z9MgzlHpgx2L47gTrFx0SgwIPnNr7bHX8Lb2/82ScHOXP+xT3jBubzgoGc8D0CYWZ6/GEvEwJLdNFG8MCCqE5T2IbdUuUQc16ps9u5vupidn0OubHs9eybDIvPe4iviHY2i3BVmZlMO2DIAqFqBExkQK68wTMlw2Mko9TkUyTUv+7Mh9EPUV126uTUZV/2UeyOug6pTv5twH4hkC/w8I6Tf2zrqnAy9Ot0tWGNvWbA8FTB313szp4BQ6IgbYLa7LXxl1YyU1bQA6bm7lxC8RWG44vHfARSiZd11EUMVvwHt9TpUljEQ8w44SLjAKzI123ph3DOuRrfDy4Qm37qEyx4lRicLsixspXUBZQ==
  template:
    metadata:
      name: rabbitmq-secret
      namespace: feedback-dev
    type: Opaque
