---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-secret
  namespace: feedback-dev
spec:
  encryptedData:
    url: AgBV+BJpC0bikgMvmguAtaI53nnnXvp6QoFR5Im6ysKNBKuvr/N/krBa5N57bkvVQWnG9SWnxzlalrsoV6twWdVnTEqs0Z7A2cQv3o2Gcaq7hMd3IrVH2TnC6E8vp8K3JipYwjdf2uzBRSzLBSCLcSvoHEXjjns5Mlv2y9b6+VK41E7Wo5XaoQf298IjSvWZFaKeXKuyLR8w4abfU0NghziOt1atfi112duzT4l5QuEqIIfpuF9Qg4rbq26Y98qVNVzd4MTJDRffpuarHPR8yoaEpKEPpAZCSNEyiOVAUHdRpISJ3QW9I/xYAJ61DCprwXGyXb/hsIERA/9ZzuCk+24Z0tYpxVptTCrY9VTfWjkKg19pXzdeeJecGB0r+HX+ydVmUkWzMqgREldAI9nn2ay2qTt+n89dhMuUJr9ewzEkLEQLErayogAGaUzf7GRDxByrFNF/KhT6KLWcoT1eNCHg2w+FfmBj0XwAN8vfce+yL4NHDPR93T8yrVnX/aXIgESn8wYi6hUfyGyx+RfcqXFNApaZCCtWZ3ZU5HZ5sTdZ38MyN586REs7XKMOteZCy1414/9IDhYW+a4rkclrYIQCRH8kze+zRk6f6fPOgapFDzvGsrZrh1HlhvIYAZyW1c2ZhGHXu591j0ZsFGSIYXdkGhGJwuzpHQf1tRYHjqnD7ltpaM9hzviE9CjKBTNR1KUKZwlOa7sOWqNNH1lP+bVsLHtIArV3fJrR7KzrqSFYSl4=
  template:
    metadata:
      name: rabbitmq-secret
      namespace: feedback-dev
    type: Opaque
