---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-auth
  namespace: feedback-dev
spec:
  encryptedData:
    password: AgBZTgLN/rM/FvW/XPXgygxiF8kAgkFwCR64Hc/r82y6nFL+YcPOF1GxfwMoDmdQldZ80qnN77KmRU/qgeT/EfcDZSYaShE1tyFy036yRZRsbQ5UqHn9xK1swj8tXv8/xoDWpGrKOmUvpNRjYPdvHvdoI8/9ZYuEKJtrJpP1hRUo9dFaUBbOO7aJqmJIregnhIJC+He5IkOCTpKFjY2zfOynjyWWg3v3uo3H0lNFMtNQ90SzykvXyxPxND22Sn0kl+5Cqjsf8b0OJO7dkhIWilxipruRMUXKvW0WKR1R2GFl6cX5KEZjl6DLlVaJZfyUeb25sa3vyulgYf1itOtxtwZWpi+n19N55iumx+yiqHficIprc3lqSYJ/u6bmVvgjpQmKEWmZRlPmOSZOKNckxDiohOiy/4p6pLD7pg+rMhtfy9xgtY4PXn3gq6vnKu83MX/vZ1LM3WnKCkLvzVa7vhgpIdZ8yAJpD5o+DgNvJFIHFp5gG1qyGRJ1LXdpnR0ySIWuxRDqKVC/7kCUOrGZtu8x8pJeXmK4suBJ51C5NueKbjAnbd/ds/Fv16yZK4bn6s1IM4K72SV4miaYZE+oKm+a78K+Z65NWMPw1DkuK4NhvY/Gd0tS0Fl+FoeS9rnaE5son/47N2m0VJVpxcCjdH7QVERN2mQvLw/GAjfTiHGuSo8iSbcFBw5T7K3qpdtHpLbwJQ7IqyzCJ2+LcRc=
    username: AgA2P4oVnn2CnsiI0Kgkoi0lSyAIFi0/bJrewqBFGig5gEmIxMaRJmHu0pzSgfjGi9WS6uPV5FxSZcJ6hFJ63b1l5qS8BRgimTBUa94ro809r2R7CJ7LIYNuHfVEAbU7ed23wcqW5B/McMrOWFfzzx3YWfKIVzfzrLhtcWWIohnzmsjktgVFEuIQPUOh/wQtFJwdaKeEiag6l0D6YJwReb9h11Beb03QSzDiJlIICZu0dC/1laLdbheaXAZ/JqPHqoQ6pc/7J308SdM3Fj/GlME+QQSk6xbzF0MT3GUMB6y4nXTWpulp6gpsigCYAQ3BWtjOI96hZLMlXhIkgkVZNScr7b+3LrxqcvNrk3D3YqgL+8/QV+/uHAc460UvQskq6D9SGaxkwOADyFHTwZijRqGPkWt5TmOTc7+GpaL+aE8sBw6qJ6Wt2xVz+mD7aoA0aOkjgHyo0mHI3Psf77/l1GdIwqz1D3VNkdwqvi/JjXcmzY9gBeE3WB0r+q0JJuNkyK67cuR/ZjGbpxGB35MbW0cYMkDiTitp6mPZViODAXdIWf7vl+M6j3NbVC6CwQPXsJbs+sdqXz+g4i2tRYzRcosaewBhMYih+Py7hK9y7VgkVrkG6Xic99d+bKPy8a3rUVaTtAYTZYmVZw2ZyKKFZTRIc/rFQLnLuXM84+NlaGpujM4SwtpKRu989t/4KRVgJ6+q5KZedA==
  template:
    metadata:
      name: rabbitmq-auth
      namespace: feedback-dev
