apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret 
  namespace: feedback-dev
type: Opaque
stringData:
  url: amqp://guest:guest@rabbitmq:5672/  # Base64 for "amqp://guest:guest@rabbitmq:5672/"
